### ISSUE TITLE
print keyword usage functional for python3?

### ISSUE THREAD

**Issue by Synaps3** [johnyf/pyan#8]
Having trouble getting anything in this module to execute because it syntax errors on every print statement in python-38

Front page claims this is a python3 package but the code is full of python2 syntax including references to the deprecated compiler package and usage of the print keyword instead of the print() function.

How is this supposed to be used with python3

**Comment by johnyf** [comment]
As of a16f5d5124e1e3a696b0402347fe7f8fdd171a58 I could not find any Python 2 style `print` statements. All `print` occurrences are function calls. The module works with branch `typing` for me (4ad92e682b9e694d25b9839bb67c004fca90ff96). Could you point to any specific line of code in that commit (which is on branch `master`) that contains old-style `print` statements?

**Comment by Synaps3** [comment]
The issue was I had overlapping package installations from doing the manual install and it wasn't using these files at all.  Resolved. Thanks for getting me to look closer.
